### ISSUE TITLE
The real question is, whether Kevin is DOM or not.

### ISSUE THREAD

**Issue by AllenWang314** [fionaxc/alphaDOM#2]
Me thinks no. But maybe that's just me. Please confirm @fionaxc 

This looks good to merge.

**Comment by katherinehe8** [comment]
![Screenshot 2024-08-28 at 6 46 13 PM](https://github.com/user-attachments/assets/0a31a1f9-d2ee-4718-b167-11c98ab25ab3)

**Comment by fionaxc** [comment]
negative.

**Comment by ccai1** [comment]
👅👅👅

**Comment by ccai1** [comment]
u like dat

**Comment by AllenWang314** [comment]
I miss app name 

Make åppnamé great again
